# https://help.github.com/en/articles/workflow-syntax-for-github-actions

name: Ubuntu18-connecter

on:
- push

jobs:
  ssh-rfc4716:
    name: Connect to github.com (RFC4716 format)
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-18.04
    steps:
    - name: Checkout source codes
      uses: actions/checkout@v2
    - name: Install SSH key
      uses: ./.
      with:
        key: ${{ secrets.SSH_KEY_RFC4716 }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
    - name: print created files
      run: ls -l ~/.ssh
    - name: git clone through SSH
      run: git clone git@github.com:8NEZNhg7U73i/ssh-key-action.git tmp
    - name: ssh test
      run: ssh -o BatchMode=yes -o PasswordAuthentication=no root@${{ secrets.SSH_HOST0 }} -p ${{ secrets.SSH_PORT0 }} ls -aln

  known_hosts-unnecessary:
    name: without known_hosts file
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-18.04
    steps:
    - name: Checkout source codes
      uses: actions/checkout@v2
    - name: Install SSH key
      uses: ./.
      with:
        key: ${{ secrets.SSH_KEY_PEM }}
        known_hosts: unnecessary
    - name: print created files
      run: ls -l ~/.ssh
    - name: host key verification disable
      run: sudo bash -c "    StrictHostKeyChecking no" >> /etc/ssh/ssh_config
    - name: git clone through SSH
      run: git clone git@github.com:8NEZNhg7U73i/ssh-key-action.git tmp
    - name: ssh test
      run: ssh -o BatchMode=yes -o PasswordAuthentication=no root@${{ secrets.SSH_HOST0 }} -p ${{ secrets.SSH_PORT0 }} ls -aln
