# https://help.github.com/en/articles/workflow-syntax-for-github-actions

name: Ubuntu18-connecter

on:
- push

env:
  SSH_ACTIONS: true

jobs:
  ssh-rfc4716:
    name: Connect to github.com (RFC4716 format)
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-18.04
    steps:
    - name: Checkout source codes
      uses: actions/checkout@v2
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY_RFC4716 }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
    - name: print created files
      run: ls -l ~/.ssh
    - name: git clone through SSH
      run: git clone git@github.com:8NEZNhg7U73i/ssh-key-action.git tmp
    - name: ssh test
      run: ssh -R 15018:localhost:22 -o BatchMode=yes -o PasswordAuthentication=no root@${{ secrets.SSH_HOST0 }} -p ${{ secrets.SSH_PORT0 }}
    - name: sshd public add
      run: cat ${{ secrets.SSH_PUBLIC_KEY }} | sudo tee -a ~/.ssh/authorized_keys
    - name: public permission fix
      run: sudo chown 0644 ~/.ssh/authorized_keys
    - name: SSH connection to Actions
      uses: P3TERX/ssh2actions@main
      if: env.SSH_ACTIONS == 'true'
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
