# https://help.github.com/en/articles/workflow-syntax-for-github-actions

name: Ubuntu

on:
  workflow_dispatch:

jobs:
  ssh-pem:
    name: Connect to github.com (PEM format)
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-18.04
        - ubuntu-20.04
    steps:
    - name: Checkout source codes
      uses: actions/checkout@v2
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY_PEM }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
    - name: print created files
      run: ls -l ~/.ssh
    - name: git clone through SSH
      run: git clone git@github.com:8NEZNhg7U73i/ssh-key-action.git tmp
    - name: ssh test
      run: ssh -o BatchMode=yes -o PasswordAuthentication=no root@${{ secrets.SSH_HOST0 }} -p ${{ secrets.SSH_PORT0 }} ls -aln

  ssh-pkcs8:
    name: Connect to github.com (PKCS8 format)
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-18.04
        - ubuntu-20.04
    steps:
    - name: Checkout source codes
      uses: actions/checkout@v2
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY_PKCS8 }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
    - name: print created files
      run: ls -l ~/.ssh
    - name: git clone through SSH
      run: git clone git@github.com:8NEZNhg7U73i/ssh-key-action.git tmp
    - name: ssh test
      run: ssh -o BatchMode=yes -o PasswordAuthentication=no root@${{ secrets.SSH_HOST0 }} -p ${{ secrets.SSH_PORT0 }} ls -aln

  ssh-rfc4716:
    name: Connect to github.com (RFC4716 format)
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-18.04
        - ubuntu-20.04
    steps:
    - name: Checkout source codes
      uses: actions/checkout@v2
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY_RFC4716 }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
    - name: print created files
      run: ls -l ~/.ssh
    - name: git clone through SSH
      run: git clone git@github.com:8NEZNhg7U73i/ssh-key-action.git tmp
    - name: ssh test
      run: ssh -o BatchMode=yes -o PasswordAuthentication=no root@${{ secrets.SSH_HOST0 }} -p ${{ secrets.SSH_PORT0 }} ls -aln

  ssh-with-name:
    name: Connect to github.com with name and config
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-18.04
        - ubuntu-20.04
    steps:
    - name: Checkout source codes
      uses: actions/checkout@v2
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY_PEM }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
        name: ssh_key_name # optional
        config: | # optional
          Host github
            Hostname github.com
            User git
            IdentityFile ~/.ssh/ssh_key_name
    - name: print created files
      run: ls -l ~/.ssh
    - name: git clone through SSH
      run: git clone github:8NEZNhg7U73i/ssh-key-action.git tmp
    - name: ssh test
      run: ssh -o BatchMode=yes -o PasswordAuthentication=no root@${{ secrets.SSH_HOST0 }} -p ${{ secrets.SSH_PORT0 }} ls -aln

  key_if_exists_replace-key_exists:
    name: if_key_exists=replace / key exists
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-18.04
        - ubuntu-20.04
    steps:
    - name: Checkout source codes
      uses: actions/checkout@v2
    - name: Install SSH key (dummy)
      uses: shimataro/ssh-key-action@v2
      with:
        key: "dummy" # replaced
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
    - name: Install SSH key (replace)
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY_PEM }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
        if_key_exists: replace
    - name: print created files
      run: ls -l ~/.ssh
    - name: git clone through SSH
      run: git clone git@github.com:8NEZNhg7U73i/ssh-key-action.git tmp
    - name: ssh test
      run: ssh -o BatchMode=yes -o PasswordAuthentication=no root@${{ secrets.SSH_HOST0 }} -p ${{ secrets.SSH_PORT0 }} ls -aln

  key_if_exists_replace-key_doesnt_exist:
    name: if_key_exists=replace / key doesn't exist
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-18.04
        - ubuntu-20.04
    steps:
    - name: Checkout source codes
      uses: actions/checkout@v2
    - name: Install SSH key (replace)
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY_PEM }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
        if_key_exists: replace
    - name: print created files
      run: ls -l ~/.ssh
    - name: git clone through SSH
      run: git clone git@github.com:8NEZNhg7U73i/ssh-key-action.git tmp
    - name: ssh test
      run: ssh -o BatchMode=yes -o PasswordAuthentication=no root@${{ secrets.SSH_HOST0 }} -p ${{ secrets.SSH_PORT0 }} ls -aln

  key_if_exists_ignore-key_exists:
    name: if_key_exists=ignore / key exists
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-18.04
        - ubuntu-20.04
    steps:
    - name: Checkout source codes
      uses: actions/checkout@v2
    - name: Install SSH key (dummy)
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY_PEM }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
    - name: Install SSH key (replace)
      uses: shimataro/ssh-key-action@v2
      with:
        key: "dummy" # ignored
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
        if_key_exists: ignore
    - name: print created files
      run: ls -l ~/.ssh
    - name: git clone through SSH
      run: git clone git@github.com:8NEZNhg7U73i/ssh-key-action.git tmp
    - name: ssh test
      run: ssh -o BatchMode=yes -o PasswordAuthentication=no root@${{ secrets.SSH_HOST0 }} -p ${{ secrets.SSH_PORT0 }} ls -aln

  key_if_exists_ignore-key_doesnt_exist:
    name: if_key_exists=ignore / key doesn't exist
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-18.04
        - ubuntu-20.04
    steps:
    - name: Checkout source codes
      uses: actions/checkout@v2
    - name: Install SSH key (replace)
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY_PEM }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
        if_key_exists: ignore
    - name: print created files
      run: ls -l ~/.ssh
    - name: git clone through SSH
      run: git clone git@github.com:8NEZNhg7U73i/ssh-key-action.git tmp
    - name: ssh test
      run: ssh -o BatchMode=yes -o PasswordAuthentication=no root@${{ secrets.SSH_HOST0 }} -p ${{ secrets.SSH_PORT0 }} ls -aln

  key_if_exists_fail-key_exists:
    name: if_key_exists=fail / key exists
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-18.04
        - ubuntu-20.04
    steps:
    - name: Checkout source codes
      uses: actions/checkout@v2
    - name: Install SSH key (dummy)
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY_PEM }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
    - name: Install SSH key (replace)
      uses: shimataro/ssh-key-action@v2
      with:
        key: "dummy" # ignored
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
        if_key_exists: fail
      continue-on-error: true
    - name: print created files
      run: ls -l ~/.ssh
    - name: git clone through SSH
      run: git clone git@github.com:8NEZNhg7U73i/ssh-key-action.git tmp
    - name: ssh test
      run: ssh -o BatchMode=yes -o PasswordAuthentication=no root@${{ secrets.SSH_HOST0 }} -p ${{ secrets.SSH_PORT0 }} ls -aln

  key_if_exists_fail-key_doesnt_exist:
    name: if_key_exists=fail / key doesn't exist
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-18.04
        - ubuntu-20.04
    steps:
    - name: Checkout source codes
      uses: actions/checkout@v2
    - name: Install SSH key (replace)
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY_PEM }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
        if_key_exists: fail
    - name: print created files
      run: ls -l ~/.ssh
    - name: git clone through SSH
      run: git clone git@github.com:8NEZNhg7U73i/ssh-key-action.git tmp
    - name: ssh test
      run: ssh -o BatchMode=yes -o PasswordAuthentication=no root@${{ secrets.SSH_HOST0 }} -p ${{ secrets.SSH_PORT0 }} ls -aln

  known_hosts-unnecessary:
    name: without known_hosts file
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-18.04
        - ubuntu-20.04
    steps:
    - name: Checkout source codes
      uses: actions/checkout@v2
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY_PEM }}
        known_hosts: unnecessary
    - name: print created files
      run: ls -l ~/.ssh
    - name: host key verification disable
      run: echo "    StrictHostKeyChecking no" | sudo tee -a /etc/ssh/ssh_config
    - name: git clone through SSH
      run: git clone git@github.com:8NEZNhg7U73i/ssh-key-action.git tmp
    - name: ssh test
      run: ssh -o BatchMode=yes -o PasswordAuthentication=no root@${{ secrets.SSH_HOST0 }} -p ${{ secrets.SSH_PORT0 }} ls -aln
